name: chat_app
description: تطبيق محادثة احترافي بـ Flutter و Supabase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # Backend
  supabase_flutter: any
  
  # UI & Theme
  google_fonts: any
  glassmorphism: ^3.0.0
  flutter_animate: any

  # Images & Files
  image_picker: any
  cached_network_image: any
  
  # Utils
  intl: any
  timeago: any
  uuid: any
  
  # Permissions
  permission_handler: any
  
  # File Picker
  file_picker: any
  
  # Path
  path_provider: any
  
  # Connectivity
  connectivity_plus: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 23
  remove_alpha_ios: true
  adaptive_icon_background: "#1E88E5"
  adaptive_icon_foreground: "assets/images/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.png
